apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-utbetalingsoversikt-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-utbetalingsoversikt-api-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-utbetalingsoversikt-api/internal/isAlive
    initialDelay: 15
  readiness:
    path: /tms-utbetalingsoversikt-api/internal/isReady
    initialDelay: 15
  prometheus:
    enabled: true
    path: /tms-utbetalingsoversikt-api/metrics
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: sokos-utbetaldata
          namespace: okonomi
          cluster: prod-fss
      external:
        - host: sokos-utbetaldata.prod-fss-pub.nais.io
    inbound:
      rules:
        - application: tms-utbetalingsoversikt-frontend
        - application: tms-min-side
  ingresses:
    - "https://person.nav.no/tms-utbetalingsoversikt-api"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: '*.nav.no'
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: POST_LOGOUT_URL
      value: https://www.nav.no
    - name: SOKOS_UTBETALDATA_URL
      value: https://sokos-utbetaldata.prod-fss-pub.nais.io/utbetaldata/api/v2
    - name: SOKOS_UTBETALING_TOKENX_CLIENT_ID
      value: prod-fss:okonomi:sokos-utbetaldata
