apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-utbetalingsoversikt-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-utbetalingsoversikt-api-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-utbetalingsoversikt-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-utbetalingsoversikt-api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  tokenx:
    enabled: true
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.dev.nav.no"
    sidecar:
      enabled: true
      level: Level3
  accessPolicy:
    outbound:
      rules:
        - application: sokos-utbetaldata
          namespace: okonomi
          cluster: dev-fss
      external:
        - host: sokos-utbetaldata.dev-fss-pub.nais.io
  ingresses:
    - "https://tms-utbetalingsoversikt-api.dev.nav.no/tms-utbetalingsoversikt-api"
    - "https://www.intern.dev.nav.no/tms-utbetalingsoversikt-api"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 384Mi
