apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-utbetalingsoversikt-api
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-utbetalingsoversikt-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-utbetalingsoversikt-api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-utbetalingsoversikt-api/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: sokos-utbetaldata
          namespace: okonomi
          cluster: dev-fss
      external:
        - host: sokos-utbetaldata.dev-fss-pub.nais.io
  ingresses:
    - "https://www.intern.dev.nav.no/tms-utbetalingsoversikt-api"
    - "https://www.ansatt.dev.nav.no/tms-utbetalingsoversikt-api"
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: "*.dev.nav.no"
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: ENABLE_DEBUG_API
      value: "true"
    - name: POST_LOGOUT_URL
      value: https://www.intern.dev.nav.no/
    - name: SOKOS_UTBETALDATA_URL
      value: https://sokos-utbetaldata.dev-fss-pub.nais.io/utbetaldata/api/v2
    - name: SOKOS_UTBETALING_TOKENX_CLIENT_ID
      value: dev-fss:okonomi:sokos-utbetaldata


